name: CI

on: [push, pull_request]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: PHPUnit Tests
        uses: php-actions/composer@v5
        with:
          bootstrap: vendor/autoload.php
          php_version: 7.1
          configuration: phpunit.xml
          args: --coverage-text