name: CI

on: [push, pull_request]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup composer
        uses: php-actions/composer@v5
        with:
          php_version: 7.1