name: CI

on: [push, pull_request]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: php-actions/composer@v5

      - name: PHPUnit Tests
        uses: php-actions/phpunit@v6
        with:
          bootstrap: tests/bootstrap.php
          php_version: 7.1
          php_extensions: json
          configuration: phpunit.xml
          args: --coverage-text